# Email from the hooks. Sent with pony

# from: warehouse@test.com # email address the email is from
# via: :smtp # either :smtp or :sendmail
# via_options:
#   host:     smtp.yourserver.com  # smtp server
#   port:     25            # smtp server port
#   auth:     :plain        # :plain, :login, :cram_md5, :none, no auth by default
#   username: user          # username
#   password: pass          # password
#   enable_starttls_auto: true  # use TLS, needed for Gmail
#   domain:   example.com   # the HELO domain provided by the client to the server
# OR for sendmail
# from: warehouse@test.com # email address the email is from
# via: :smtp # either :smtp or :sendmail
# via_options:
#    location: /usr/bin/sendmail # this defaults to 'which sendmail' or '/usr/sbin/sendmail' if 'which' fails


# This default config brought to you by MockSMTP for Mac
from: warehouse@test.com
via: :smtp
via_options:
  host:     localhost
  port:     1025
  domain:   example.com